tap "homebrew/bundle"
tap "homebrew/cask"
tap "homebrew/core"
brew "bat"
brew "mas"
brew "n"
brew "zsh"
cask "caffeine"
cask "docker"
cask "gitkraken"
cask "google-chrome"
cask "slack"
cask "rectangle"
cask "spotify"
cask "visual-studio-code"
mas "WhatsApp", id: 1147396723
