tap "homebrew/bundle"
tap "homebrew/cask"
tap "homebrew/cask-versions"
tap "homebrew/core"
brew "bat"
brew "mas"
brew "tig"
brew "zsh"
cask "fig"
cask "google-chrome"
cask "rectangle"
cask "slack"
cask "spotify"
cask "visual-studio-code"
mas "1Password 7", id: 1333542190
